" vim config
" mostly shit stolen from other places

" vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'chrisbra/Recover.vim'
Plugin 'chrisbra/SudoEdit.vim'
Plugin 'ConradIrwin/vim-bracketed-paste'
Plugin 'thinca/vim-localrc'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-sleuth'
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-session'

call vundle#end()
filetype plugin indent on

" sanity
set magic
set fileencoding=utf-8
set nobackup
set visualbell t_vb=""

" other basic settings
set background=dark
set dir=~/.vim/tmp
syntax on

" default indentation settings
set softtabstop=4
set shiftwidth=4
set expandtab
set backspace=indent,eol,start
set list listchars=tab:»\ ,trail:·

" wildmenu
set wildmode=longest:full
set wildmenu

" search related stuff
set showmatch
set incsearch
set hlsearch

" clear hlssearch with \n
nmap <silent> <leader>n :silent :nohlsearch<CR>

" avoid slowdowns
set synmaxcol=400

" use the X clipboard if possible
set clipboard=unnamedplus

" virtualedit
set virtualedit=block
noremap j gj
noremap k gk

" goddamn capitals
cabbr W w
cabbr Q q
cabbr wQ wq
cabbr WQ wq
cabbr Wq wq

" indentation styles for different formats
"au FileType xhtml setlocal sts=2 ts=2 sw=2
"au FileType html setlocal sts=2 ts=2 sw=2
"au FileType htmldjango setlocal sts=2 ts=2 sw=2
"au FileType c setlocal sts=0 ts=8 sw=8 noexpandtab cindent
"au FileType cpp setlocal sts=0 ts=8 sw=8 noexpandtab

" colors
set t_Co=256
colorscheme wombat256roger

" really really bright highlights of stuff i shouldn't push
highlight XXXDX ctermfg=black ctermbg=red 
let g:xxxdx = matchadd("XXXDX", "XXXDX")

" highlight after 80 cols (only for python code)
highlight ExtraWhitespace ctermbg=215 ctermfg=black
"highlight ExtraWhitespace2 ctermbg=202 ctermfg=black

function! HighlightAfter80Cols()
    let w:m1=matchadd('ExtraWhitespace', '\%<81v.\%>80v', -1)
    "let w:m2=matchadd('ExtraWhitespace2', '\%>80v.\+', -1)
    "let w:m3=matchadd('ExtraWhitespace2', '\%>80v.\+', -1)
endfunction

au FileType python call HighlightAfter80Cols() 

" SudoEdit.vim
noremap ss :w sudo:%<CR>

" matchit (builtin)
runtime macros/matchit.vim

" nerdtree
map <F2> :NERDTreeToggle<CR>
let NERDTreeIgnore=['\.pyc$']

" syntastic
let g:syntastic_python_checkers = ['pyflakes']
let g:syntastic_c_checkers = ['gcc']

let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': [],'passive_filetypes': [] }
nnoremap <C-w>E :SyntasticCheck<CR> :SyntasticToggleMode<CR>

" localrc
let g:localrc_filename = '.vim.custom'

" vala 
autocmd BufRead *.vala,*.vapi set efm=%f:%l.%c-%[%^:]%#:\ %t%[%^:]%#:\ %m
au BufRead,BufNewFile *.vala,*.vapi setfiletype vala

" recover plugin
let g:RecoverPlugin_Edit_Unmodified = 1

function! DxTodoPostprocess()
    let l:winview = winsaveview()
    %!~/test/dxtodo/postprocess
    call winrestview(l:winview)
endfunction

" what am i even doing
autocmd BufRead dxtodo setlocal sts=30 ts=30 sw=30 noet
autocmd BufWrite dxtodo call DxTodoPostprocess()

" session

let g:session_autosave = 'no'
let g:session_autoload = 'no'
let g:session_command_aliases = 1
