#!/bin/sh
echo '{"command": "gpu", "parameter": "0"}' | nc localhost 4028 | jshon -e GPU -e 0 -e Intensity -u -p -e Temperature -u -p -e "MHS 5s" -u | paste -sd "\t" | sed -r 's/^([0-9]*)\t([0-9]*)\.[0-9]*\t0.([0-9]{3}).*$/I=\1, \2°, \3kh/'

